In [32]:
import pandas as pd

df = pd.read_csv('../data/curated/realestate_with_closest_distance_duration.csv')
df

,id,address,suburb,postcode,price,propertyType,bedrooms,bathrooms,parkingSpaces,studies,...,closest_tram_distance,closest_tram_duration,closest_bus_lat,closest_bus_long,closest_bus_distance,closest_bus_duration,closest_park_lat,closest_park_long,closest_park_distance,closest_park_duration
0,435045151,2109/33 MacKenzie St,Melbourne,3000,560,Apartment,2,1,0,0,...,688.1,105.4,-37.807495,144.965637,136.5,19.5,-37.797682,144.968679,1410.7,177.2
1,435045047,2108/11 Rose Lane,Melbourne,3000,580,Apartment,2,1,0,0,...,227.7,41.4,-37.814288,144.955124,522.3,88.1,-37.818786,144.969296,2518.5,340.5
2,435144851,3210/9-23 Mackenzie Street,Melbourne,3000,450,Apartment,1,1,0,0,...,238.2,40.7,-37.806954,144.968752,237.6,41.4,-37.797682,144.968679,1417.0,181.7
3,435144711,300/668 Bourke Street,Melbourne,3000,550,Apartment,2,2,1,0,...,491.7,74.8,-37.814821,144.952077,625.0,83.5,-37.818786,144.969296,2203.4,290.5
4,435044255,2108/11 Rose Lane,Melbourne,3000,600,Apartment,2,1,0,0,...,227.7,41.4,-37.814288,144.955124,522.3,88.1,-37.818786,144.969296,2518.5,340.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10417,433277390,102-104 Ridge Road,Mount Dandenong,3767,750,House,3,2,6,0,...,24834.9,1885.1,-37.833291,145.350727,8.8,0.6,-37.832689,145.355490,1524.7,174.5
10418,434646035,A/25 Springs St,Cockatoo,3781,300,House,1,1,1,0,...,41895.0,2824.7,-37.936334,145.487397,1023.2,217.2,-37.935276,145.465820,4077.9,667.9
10419,435115059,40 Fairway Rd,Emerald,3782,680,House,3,2,2,1,...,38172.9,2511.3,-37.921527,145.469976,1149.6,146.0,-37.928784,145.468303,2423.3,405.6
10420,434812399,5 Florence Av,Emerald,3782,490,House,3,1,1,0,...,36500.0,2408.5,-37.927689,145.445705,1531.3,186.2,-37.907092,145.441522,1771.8,160.4
10421,435120239,28 Monash Ave,Olinda,3788,495,House,3,1,0,0,...,23209.5,1889.7,-37.855183,145.364379,242.5,58.2,-37.850913,145.363467,242.5,58.2

In [33]:
# Want to predict the price of a property aggregated by suburb, property type and bedrooms

gb = df.groupby(["suburb","propertyType","bedrooms"]).mean()
gb.columns

Index(['id', 'postcode', 'price', 'bathrooms', 'parkingSpaces', 'studies',
       'latitude', 'longitude', 'closest_primary_lat', 'closest_primary_long',
       'closest_primary_distance', 'closest_primary_duration',
       'closest_secondary_lat', 'closest_secondary_long',
       'closest_secondary_distance', 'closest_secondary_duration',
       'closest_train_lat', 'closest_train_long', 'closest_train_distance',
       'closest_train_duration', 'closest_tram_lat', 'closest_tram_long',
       'closest_tram_distance', 'closest_tram_duration', 'closest_bus_lat',
       'closest_bus_long', 'closest_bus_distance', 'closest_bus_duration',
       'closest_park_lat', 'closest_park_long', 'closest_park_distance',
       'closest_park_duration'],
      dtype='object')

In [34]:
sub = gb[['price', 'closest_primary_duration','closest_secondary_duration', 'closest_train_duration', 'closest_tram_duration', 'closest_bus_duration', 'closest_park_duration']]

In [35]:
sub

                                       price  closest_primary_duration  \
suburb     propertyType bedrooms
Abbotsford Apartment    1         416.000000                175.580000
                        2         547.307692                120.569231
           House        2         636.250000                147.050000
                        3         725.000000                177.700000
           Townhouse    2         595.000000                237.200000
...                                      ...                       ...
Yarraville Townhouse    2         521.666667                140.983333
                        3         630.000000                112.250000
                        4         890.000000                103.200000
           Unit         1         155.000000                 63.500000
                        2         480.000000                118.900000

                                  closest_secondary_duration  \
suburb     propertyType bedrooms
Abbotsford Apartment    1                         201.080000
                        2                         166.900000
           House        2                         150.400000
                        3                         177.700000
           Townhouse    2                         237.200000
...                                                      ...
Yarraville Townhouse    2                         430.216667
                        3                         480.250000
                        4                         339.700000
           Unit         1                         398.900000
                        2                         493.100000

                                  closest_train_duration  \
suburb     propertyType bedrooms
Abbotsford Apartment    1                     200.000000
                        2                     171.815385
           House        2                     131.475000
                        3                     181.600000
           Townhouse    2                     205.000000
...                                                  ...
Yarraville Townhouse    2                     139.450000
                        3                     151.450000
                        4                     234.300000
           Unit         1                     143.400000
                        2                     171.000000

                                  closest_tram_duration  closest_bus_duration  \
suburb     propertyType bedrooms
Abbotsford Apartment    1                    139.400000                 93.52
                        2                     51.584615                204.70
           House        2                    132.350000                 75.35
                        3                    215.200000                145.10
           Townhouse    2                    241.400000                 54.20
...                                                 ...                   ...
Yarraville Townhouse    2                    284.050000                 43.45
                        3                    359.850000                 58.80
                        4                    279.000000                 16.70
           Unit         1                    267.500000                 20.90
                        2                    371.400000                 11.00

                                  closest_park_duration
suburb     propertyType bedrooms
Abbotsford Apartment    1                    228.560000
                        2                    134.369231
           House        2                    232.475000
                        3                    269.500000
           Townhouse    2                    297.300000
...                                                 ...
Yarraville Townhouse    2                    220.133333
                        3                    240.850000
                        4                    335.300000
           Unit         1                    243.600000
                        2                    168.000000

[2265 rows x 7 columns]

In [36]:
from statsmodels.formula.api import ols, glm, wls
from statsmodels.api import families


model = ols(formula="""price ~ closest_train_duration + closest_tram_duration + closest_bus_duration + closest_park_duration
                                    """,
            data=sub)

model.fit().summary()

# Model interpretation:
# 
# Effect of suburb properties on rental income, after accounting for property type and bedroom count
#
# Train station distance has no effect
# Properties close to tram stops are valued more
# Properties further from bus stops are valued more
# Properties close to parks are valued more

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.076
Model:                            OLS   Adj. R-squared:                  0.074
Method:                 Least Squares   F-statistic:                     46.25
Date:                Mon, 03 Oct 2022   Prob (F-statistic):           2.10e-37
Time:                        16:08:54   Log-Likelihood:                -15421.
No. Observations:                2265   AIC:                         3.085e+04
Df Residuals:                    2260   BIC:                         3.088e+04
Df Model:                           4
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                629.1086     11.962     52.594      0.000     605.652     652.565
closest_train_duration     0.0011      0.026      0.043      0.965      -0.051       0.053
closest_tram_duration     -0.0784      0.009     -8.645      0.000      -0.096      -0.061
closest_bus_duration       0.5013      0.085      5.893      0.000       0.334       0.668
closest_park_duration     -0.1683      0.020     -8.406      0.000      -0.208      -0.129
==============================================================================
Omnibus:                      804.893   Durbin-Watson:                   1.489
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3371.421
Skew:                           1.687   Prob(JB):                         0.00
Kurtosis:                       7.933   Cond. No.                     2.45e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.45e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [37]:

model = ols(formula="""price ~ closest_primary_duration + closest_secondary_duration""",
            data=sub)

model.fit().summary()

# Model interpretation:
# 
# Effect of suburb properties on rental income, after accounting for property type and bedroom count
#
# Primary school distance has no effect
# Properties closer to public secondary schools are valued more

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.005
Method:                 Least Squares   F-statistic:                     7.238
Date:                Mon, 03 Oct 2022   Prob (F-statistic):           0.000736
Time:                        16:08:54   Log-Likelihood:                -15503.
No. Observations:                2265   AIC:                         3.101e+04
Df Residuals:                    2262   BIC:                         3.103e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                    572.0266     11.724     48.792      0.000     549.036     595.017
closest_primary_duration      -0.0234      0.059     -0.393      0.695      -0.140       0.093
closest_secondary_duration    -0.1309      0.039     -3.314      0.001      -0.208      -0.053
==============================================================================
Omnibus:                      865.312   Durbin-Watson:                   1.382
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3634.160
Skew:                           1.832   Prob(JB):                         0.00
Kurtosis:                       8.009   Cond. No.                         807.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""